### ISSUE TITLE
xfce4-terminal-WARNING Failed to connect to session manager

### ISSUE THREAD

**Issue by UnknownViruZ** [ServError/IL2-GB-Dedicated-Server-Docker#1]
After using the compose command i get the warning: "Failed to connect to the session manager: SESSION_MANAGER environment variable not defined" the log stops there and i cannot acces or find the webgui. Dont know how to fix it please help.

**Comment by ServError** [comment]
That warning is expected and shouldn't cause problems.  There is a default IP configured in the compose file. Are you able to talk to any of the services on it?

**Comment by UnknownViruZ** [comment]
I was not able to talk to the services but I found a different solution I just used windows server to set up IL-2 and now everything works. But thanks for trying to help.
